name: openhabittracker
title: OpenHabitTracker
icon: net.openhabittracker.OpenHabitTracker.svg
website: https://openhabittracker.net
source-code: https://github.com/Jinjinov/OpenHabitTracker
issues: https://github.com/Jinjinov/OpenHabitTracker/issues
license: GPL-3.0
version: '1.2.1'
grade: stable #devel
summary: Take notes, plan tasks, track habits
description: |
  - Free and Ad-Free
  - Open Source
  - Privacy Focused: All user data is stored locally on your device
  - Available on Windows, Linux, Android, iOS, macOS, and as a web app
  - Localized to English, German, Spanish, Slovenian, French, Portuguese, Italian, Japanese, Chinese, Korean, Dutch, Danish, Norwegian, Swedish, Finnish, Polish, Czech, Slovak, Croatian, Serbian

  Key Features:

  - Markdown support for notes
  - Use categories and priorities to organize your notes, tasks, and habits
  - Advanced Search, Filter, and Sort
  - Data Export/Import: JSON, YAML, TSV, Markdown
  - Import your notes from Google Keep
  - Available in 26 themes with Dark and Light modes

base: core24

confinement: strict #devmode

parts:
  openhabittracker:
    source: .
    plugin: dotnet
    # dotnet-build-configuration: Release
    # dotnet-self-contained-runtime-identifier: linux-x64
    dotnet-version: "9.0"
    dotnet-configuration: "Release"
    dotnet-build-framework: "net9.0"
    dotnet-verbosity: "normal"
    dotnet-project: OpenHabitTracker.Blazor.Photino/OpenHabitTracker.Blazor.Photino.csproj
    dotnet-properties:
      PublishSingleFile: "true"
    # build-packages:
    #   - dotnet-sdk-9.0
    override-build: |
      craftctl default
      # Replace content of .desktop file
      cp net.openhabittracker.OpenHabitTracker.desktop $CRAFT_PART_INSTALL
      sed -i "s|Exec=OpenHT|Exec=openhabittracker|g" $CRAFT_PART_INSTALL/net.openhabittracker.OpenHabitTracker.desktop
      sed -i "s|Icon=net.openhabittracker.OpenHabitTracker|Icon=$SNAP/meta/gui/icon.svg|g" \
        $CRAFT_PART_INSTALL/net.openhabittracker.OpenHabitTracker.desktop

apps:
  openhabittracker:
    extensions: [ gnome, dotnet9 ]
    command: OpenHT
    desktop: net.openhabittracker.OpenHabitTracker.desktop
    plugs:
      - hardware-observe
      - home
      - removable-media
      - network
